SECRET_KEY_BASE: YourSecretKeyBase
CORS_ORIGINS: '*'
HOST: example.com
PROTOCOL: https
DEVISE_SECRET: YourDeviseSecret
MAIL_SENDER: noreply@example.com
APP_NAME: Example App
DEVISE_PEPPER: YourDevisePepper
SENDGRID_USERNAME: YourSendgridUsername
SENDGRID_PASSWORD: YourSendgridPassword
MAIL_DOMAIN: example.com
BUGSNAG_API_KEY: YourApiKey
BUGSNAG_RELEASE_STAGE: development
FRONTEND_CONFIRMATION_URL: 'https://www.example.com/confirm?confirmation_token=%{confirmation_token}'
FRONTEND_PASSWORD_RESET_URL: 'https://www.example.com/password-reset?reset_password_token=%{reset_password_token}'
