SECRET_KEY_BASE: YourSecretKeyBase
CORS_ORIGINS: '*'
HOST: example.com
PROTOCOL: https
MAIL_SENDER: noreply@example.com
SMTP_ADDRESS: smtp.mandrillapp.com
SMTP_DOMAIN: batteries911.com
SMTP_PASSWORD: mandrill_api_key
SMTP_USERNAME: mandrill_username
MAIL_DOMAIN: example.com
BUGSNAG_API_KEY: YourApiKey
BUGSNAG_RELEASE_STAGE: development
REDIS_PROVIDER: REDIS_URL
REDIS_URL: redis://localhost:6379
ACTIONCABLE_REQUEST_ORIGINS: https://my-app.herokuapp.com # use 'false' to disable
RABBITMQ_URL: amqp://guest:guest@localhost:5672
LOG_LEVEL: debug
PUBNUB_SUBSCRIBE_KEY: YourPubnubSubscribeKey
PUBNUB_PUBLISH_KEY: YourPubnubPublishKey
PUBNUB_SECRET_KEY: YourPubnubSecretKey
