SECRET_KEY_BASE: YourSecretKeyBase
CORS_ORIGINS: '*'
HOST: example.com
PROTOCOL: https
MAIL_SENDER: noreply@example.com
SENDGRID_USERNAME: YourSendgridUsername
SENDGRID_PASSWORD: YourSendgridPassword
MAIL_DOMAIN: example.com
BUGSNAG_API_KEY: YourApiKey
BUGSNAG_RELEASE_STAGE: development
REDIS_PROVIDER: REDIS_URL
REDIS_URL: redis://localhost:6379
ACTIONCABLE_REQUEST_ORIGINS: https://my-app.herokuapp.com # use 'false' to disable
RABBITMQ_URL: amqp://guest:guest@localhost:5672
LOG_LEVEL: debug
ABLY_API_KEY: YourAblyApiKey
ABLY_CHANNELS: test1,test2
